name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: 'test'
          base_branch:
            ${{ github.event_name == 'pull_request' && github.head_ref ||
            github.ref_name }}

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.test-action.outputs.pr_url }}"
          echo "${{ steps.test-action.outputs.report }}"
